name: ci-with-development-api

on: deployment
#  push:
#    branches:
#      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
#    - name: create deployment
#      id: create_deployment
#      uses: octokit/request-action@v2.x
#      with:
#        route: POST /repos/:repository/deployments
#        repository: ${{ github.repository }}
#        mediaType: | # The | is significant!
#           previews:
#             - flash
#             - ant-man
#        ref: ${{ github.ref }}
#        environment: dev
#        auto_merge: false
#        required_contexts: '[]'
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Started ${{ github.event.deployment.environment }} ${{ github.event.deployment.task }}
      id: start-deployment
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/:repository/deployments/:deployment_id/statuses
        repository: ${{ github.repository }}
        mediaType: | # The | is significant!
           previews:
             - flash
             - ant-man
        deployment_id: ${{ github.event.deployment.id }}
        state: "in_progress"
        description: "started deploy"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Succeeded ${{ github.event.deployment.environment }} ${{ github.event.deployment.task }}
      id: succeed-deployment
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/:repository/deployments/:deployment_id/statuses
        repository: ${{ github.repository }}
        mediaType: | # The | is significant!
           previews:
             - flash
             - ant-man
        deployment_id: ${{ github.event.deployment.id }}
        state: "success"
        description: "succeeded deploy"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
