on:
  push:
    branches:
      - master

name: ci-with-development-api

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
    - name: create deployment
      id: create_deployment
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/:repository/deployments
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        environment: development
        auto_merge: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Start Deployment ${{ github.event.deployment.environment }} ${{ github.event.deployment.task }}
      id: start-deployment
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/:repository/deployments/:deployment_id/statuses
        repository: ${{ github.repository }}
        mediaType: | # The | is significant!
           previews:
             - flash
        deployment_id: ${{ github.event.deployment.id }}
        state: "in_progress"
        description: "started deploy"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
