on: workflow_dispatch

name: WorkflowDispatch1

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    timeout-minutes: 300
    steps:
    - name: debug
      run: |
        echo ${{ github.event.ref }}
